"""Restore Link model to original structure

Revision ID: 19bd74364b1a
Revises: 5099d7fc2418
Create Date: 2025-04-19 17:49:02.441143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bd74364b1a'
down_revision = '5099d7fc2418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
